### ISSUE TITLE
Generate metadata about Modules

### ISSUE THREAD

**Issue by Hookyns** [Hookyns/tst-reflect#20]
# Proposed Changes
1. Create new class `Module`
```typescript
class Module {
    // Pointer to "native" module; created by system; assigned to all native types such as number, string, Array etc..
    static readonly Native: Module;

    // Name of the module?? File name maybe..
    readonly name: string;

    // Relative path to the module
    readonly path: string;

    // List of Types exported from the module
    getExports(): Type[];

    static find(filter: (module: Module) => boolean): Module | undefined;
    static getModules(): Module[];
}
```

2. add property `module` into `Type`
```typescript
class Type{
    readonly module: Module;
    // ...
}
```
3. add new config option `reflection.metadata.modules: boolean = false`.

# Notes
This can be very handy for server usage, but somebody might find this useful on client too so it should be optional. Disabled by default.

**Comment by iDevelopThings** [comment]
I like this idea... this would probably be a better solution to my idea for include/exclude to find types, since types are just an easy way to find a module(with the problem I'm trying to solve atleast)

**Comment by Hookyns** [comment]
I think that include/exclude is still important here and maybe more important...

We can generate Module metadata about modules whose types are used in the getType<>() to save some resources but usage of the Modules would have different purpose,.. I think we want a list of all the modules. It's okay, but it is not so okay to generate metadata for all the types inside those modules. Those types should be still filtered by incluse/exclude.

Or we can make option `reflection.modules = infered | all-just-headers | all`... Ignore those names.... 
- infer is basic mode. Generate the Modules only for the types I use, cuz I want to know where they are. getExports() returns only types used by the getType().
- all-just-headers is infer + all the modules from project, but their getExports() returns [] - empty array.
- all means all but with regards to include/exclude.

Does it make any sense? 😅

**Comment by iDevelopThings** [comment]
Oh yeah definitely it is 😅 

It makes perfect sense and I love the idea, this idea is kind of the reason I came up with the "includes/excludes" stuff, because I needed something like this 😄 

It's just a harder problem to solve than I originally thought - I'm having troubles finding a decent way to include a file in the transformer, that's not supposed to be there

For example;
If you have `FileA.ts`, which only has one imported file `FileB.ts` and FileB has no imports.
Our file list is basically only `['FileA.ts', 'FileB.ts']`... but now we want to add `FileC.ts`
And all of this has to happen before the transformer runs. I kind of found a solution, but it stops the transformer from running now 😢

**Comment by Hookyns** [comment]
Wow, I think it is simple but I didn't think about it that much,..

Transformer visit all the project files. It has to. So...

1. Grab includes and excludes from config and create list of RegExps from those glob patterns. (It's a must,.. performance; no need for globing etc. to work with FS).
2. In index.ts check `if (!includeRegexes.some(regex => regex.test(node.fileName)) return;`
3. Done!

**Comment by Hookyns** [comment]
Implemented for the v1. Not in the current version.
